### ISSUE TITLE
where to post the tech memo for review?

### ISSUE THREAD

**Issue by sgaichas** [NOAA-EDAB/tech-memo#14]
Looks like we have two relatively easy options for posting a copy of the compiled tech memo for review:  [Rstudio Connect](https://bookdown.org/yihui/bookdown/rstudio-connect.html )
or [GitHub](https://bookdown.org/yihui/bookdown/github.html)
GitHub looks slightly more complicated. 
I can enable the editing feature for the book either place.
Thoughts?

**Comment by slarge** [comment]
I've been thinking about this... I really like the travis-ci workflow (commit - push to branch - pull request - verify with travis-ci - merge if OK) because it prevents pushing a breaking change to the master that will prevent the book from building. [This workflow](https://nathaneastwood.github.io/2017/05/16/automatically-building-testing-and-deploying-bookdown-with-travis-and-github-pages/
) works with GH pages, which would keep everything contained within the NOAA-EDAB/tech-memo repo. 

I think this would be a (potentially) more complicated flavor of your slightly more complicated suggestion. I'm happy to help with any of the above, but won't have much time until next Thursday

**Comment by sgaichas** [comment]
That does look ideal; I'll see what I can set up. It would be great to let people look at the draft before or at the workshop on their own computers if possible, but if I can't swing it we can just show a local version on one of our machines.

**Comment by slarge** [comment]
I agree. Perhaps the travis-ci bit is not necessary for now but we can add later (or next iteration).

**Comment by sgaichas** [comment]
if I sign up with travis-ci it has an option for "grant access" to NOAA-EDAB organization; should I do that?

**Comment by slarge** [comment]
yeah, I htink that's OK

**Comment by sgaichas** [comment]
- [ ] sign us up with Travis-CI
  -[ ] figure out security token
- [ ] set up gh-pages branch
  - [ ] create local gh-pages branch with all files removed
  - [ ] add .nojekyll
  - [ ] initial local commit to gh-pages branch
  - [ ] push local gh-pages to origin
- [ ] put the current _book output directory onto the gh pages branch
- [ ] .travis.yml file for master branch
  - [ ] sets language (R), pandoc version
  - [ ] build script
  - [ ] deploy script
- [ ] DESCRIPTION file for master branch
  - [ ] list dependencies in here (all packages used in book!)
- [ ] finish this list
- [ ]

**Comment by sgaichas** [comment]
It works! [tech memo is live](https://noaa-edab.github.io/tech-memo/index.html) 
for future we may want to streamline the number of packages and dependencies--if one R package can work instead of several that would streamline build
