### ISSUE TITLE
Tech memo editing

### ISSUE THREAD

**Issue by slarge** [NOAA-EDAB/tech-memo#15]
Check-list of edits that can be made across all indicators
- [x] Consistency with headings (e.g., ##Methods vs ## Methods)
- [ ] add other custom style file?
- [ ] fixed vs free toolbar?
- [ ] change biblio style? 
- [x] consistent treatment of code blocks
  - [x] put necessary packages into single code block up top
  - [x] maybe not session info?
  - [x] clarify if something other than R used
- [x] consistent treatment of ERDDAP (direct link or keep code block demo?)
- [x] remove remaining ###References sections
- [x] remove remaining boilerplate code left from skeleton
- [x] point of contact person: list email address?
- [x] should included code run on any machine? if so, remove references to c:/.../files
- [ ] ...

**Comment by sgaichas** [comment]
Could everyone please take a look at the [Trend Analysis](https://noaa-edab.github.io/tech-memo/trend-analysis.html) chapter to see the proposed new chapter outline? Andy has put the description, category, contributors, and PARR metadata all up into a compact leading section so that the main outline is the methods. I like this. Other thoughts? Should we implement for all sections?

**Comment by slucey** [comment]
Sarah,

I like the new format.  The commercial landings rmd is in that style and
now available.  Sorry for the delay.

Sean


Sean M. Lucey
Fisheries Biologist
Ecosystem Dynamics and Assessment Branch
U. S. Dept. of Commerce/NOAA/NMFS
Northeast Fisheries Science Center
166 Water Street, Woods Hole, MA 02543
508-495-2011 (voice)
508-495-2232 (fax)
