### ISSUE TITLE
Explore publishing SOE 2018 as a publication

### ISSUE THREAD

**Issue by slarge** [NOAA-EDAB/tech-memo#6]
[ ] Journal
[ ] ...

**Comment by sgaichas** [comment]
Proposed Outline:

Title: State of the Ecosystem: So What? Improving ecosystem reporting for fisheries managers in the Northeast US

Authors: all contributors to 2018 SOEs (also add past contributors, and Scott!)

Intro: EBFM sounds hard but it doesnt have to be, here is an example of ecosystem reporting that is useful to managers and how we did it.
initial drafts followed a format used in another region but managers wanted to know "so what". Here is how we addressed this to produce two relatively automated reports that Councils are now requesting annually. lessons learned could serve as example for other ecosystem reporting efforts.

Methods: 
build on existing efforts inside and outside the region; ESRs, SOE west coast
address OBJECTIVES, clearly align indicators with objectives (IEA process, WGNARS)
put most manager-relevant things first: HUMAN DIMENSIONS instead of salinity, etc
keep it short, <25 printed pages
keep language non-technical, don't include references etc in report
publish technical methods separately for those that are interested (see supplement here; Technical methods as individual rmarkdown documents rolled up into one bookdown.)
produce in Rmarkdown for reproducibility and ease of conversion to different reports
data in standardized format with standardized plotting
version control on github 
production process: first years, one lead asking for data from multiple people, inefficient. 2017: workshop to develop outline in August with managers to focus further, smaller working groups (human dimensions, protected species, etc) developing new section until December, when data were needed. Mid-January synthesis meeting, report production Feb, internal review, revision, and to initial Council review early March. 
present to the Council SSC (Mid) first for initial review, turn around for full Council presentation in ~1 month responding as possible to review, responding to previous year's comments explicitly
Councils receive reports in April of each year, main message is whether there are big changes in the ecosystem or other threats to achieving their objectives

Results: the SOE report itself, with parts of both reports as examples (maybe have one report and call out where the other was different)

Discussion:
Rising to the "so what" challenge improved ecosystem reporting in the NE US and has resulted in other analyses of use to managers (e.g. ref risk assessment, hopefully published by then). An effective annual process has evolved where contextual information is presented that can change multiple decisions if necessary (ref Zador, value of qualitative information). Flexibility and responsiveness to audience important, willing to change reporting as manager needs change. 
Focus on synthesis and indicators directly addressing management objectives key. Don't get rid of all other ecosystem indicators but report selectively from a "mothership" of ecosystem data (e.g. ESR on the web) for different audiences. The encyclopedic report is less useful for managers who have limited time and need the bottom line. Oceanographers want the salinity time series, fishery managers dont know what to do with them unless clearly connected to habitat of managed species or other objectives. 
Put best practices/lessons learned from IEA group WGNARS (ref DePiper et al 2017, also Levin et al 2009 other IEA lit) into actual practice. 
Automation and transparency useful not just in theory but for practical report production. Rmarkdown and github workflow efficient and traceable, allows effective collaboration. (Would be great to have SOE as html for website too and point to that)
Next steps (in progress): web access to indicator data through ERDDAP (link), retrospective documentation of past indicators, development of new indicators. Priority given to indicator selection and evaluation, threshold analysis, synthetic methods such as DFA. Keep indicator data available and accessible for synthesis, modeling, future work.
Process flexible and can be adjusted to needs in any region/management context. Maybe EBFM isn't so hard after all.
